# This file provides explicit build instructions for Netlify.
[build]
  # Specifies the command to build the project.
  command = "yarn build"
  # Specifies the directory that contains the built assets.
  publish = "dist"

[build.environment]
  # Sets a stable Node.js version for the build environment.
  NODE_VERSION = "20"
  # Ensures a specific version of Yarn is used.
  YARN_VERSION = "1.22.19"
