# This file provides explicit build instructions for Netlify,
# ensuring it uses the correct package manager and Node.js version.
[build]
  # Specifies the command to build the project.
  command = "yarn build"
  
  # Specifies the directory that contains the built assets.
  publish = "dist"

# Specifies build-time environment variables.
[build.environment]
  # Pins the Node.js version for consistent builds.
  NODE_VERSION = "20"
  
  # Pins the Yarn version for consistency.
  YARN_VERSION = "1.22.19"
